# Generated by Django 3.0 on 2019-12-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191216_1731'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousezone',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseZone',
        ),
    ]
