# Generated by Django 3.0 on 2019-12-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191216_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='DicountCode',
            new_name='DiscountCode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='point',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_place',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ManyToManyField(blank=True, to='products.DiscountCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Cart')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product_line',
            field=models.ManyToManyField(through='products.CartProductLine', to='products.ProductLine'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_line',
            field=models.ManyToManyField(through='products.OrderProductLine', to='products.ProductLine'),
        ),
    ]
