# Generated by Django 3.0 on 2019-12-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191216_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='waybill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Waybill'),
        ),
    ]
