# Generated by Django 3.0 on 2019-12-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventproductcategory',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventproductcategory',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='eventproductcategory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Event'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default='No description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='Product Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Not Available')], default=1),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Out of supply')], default=1),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Out of supply')], default=1),
        ),
    ]
