# Generated by Django 3.0 on 2019-12-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191216_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='product_category',
            field=models.ManyToManyField(to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='attribute',
            field=models.CharField(default='No attribute', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productline',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
