# Generated by Django 3.0 on 2019-12-16 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191216_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductline',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartproductline',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.CharField(blank=True, default='Delivery Place', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderproductline',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderproductline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
        migrations.AlterField(
            model_name='orderproductline',
            name='product_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine'),
        ),
        migrations.AlterField(
            model_name='orderproductline',
            name='unit_price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='config',
            field=models.TextField(default='No config', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='seri_number',
            field=models.CharField(default='Product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.WarehouseZone'),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='city',
            field=models.CharField(blank=True, default='Thanh Pho', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='district',
            field=models.CharField(blank=True, default='Quan', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='receive_name',
            field=models.CharField(blank=True, default='Ten', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='street',
            field=models.CharField(blank=True, default='Duong', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='sub_district',
            field=models.CharField(blank=True, default='Phuong', max_length=100, null=True),
        ),
    ]
