# Generated by Django 2.2 on 2019-12-18 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20191216_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiveinfo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='write',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(default='Discount Code', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderproductline',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seri_number',
            field=models.CharField(default='Product', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='Product Category', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='receive_name',
            field=models.CharField(blank=True, default='Ten', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='address_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='size',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
